#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

seq_max = 1
seq_prev = 0
seq_tmp = 0

even_sum = 0

while seq_max < 4000000:
    seq_tmp = seq_max
    seq_max += seq_prev
    seq_prev = seq_tmp
    if seq_max % 2 == 0:
        even_sum+= seq_max

print(seq_max)
